[package]
name = "substreams-ethereum-tutorial"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["cdylib"]

[dependencies]
substreams = "0.5.0"
substreams-ethereum = "0.8.0"
prost = "0.11"

[profile.release]
lto = true
opt-level = 's'
strip = "debuginfo"